### ISSUE TITLE
Zpaq support

### ISSUE THREAD

**Issue by Sanesecurity** [RichardMidnight/pi-safe#2]
Could Zpaq support be added... 

http://mattmahoney.net/dc/zpaq.html

As its got journaling built in, it may make it a good choice for snapshots and saving a lot of space. 

Thanks

**Comment by RichardMidnight** [comment]
Sanesecurity thanks for the suggestion.  I need to polish the current feature set first.  Then I can look into this.

Peace

**Comment by RichardMidnight** [comment]
Thanks for the heads up on Zpaq.
I just took a look at Zpaq.  It looks like a good compression tool for incremental backups.  Since PiSafe does a full image backup, the incremental backup functions of Zpaq are not helpful.  I ran a quick test and Zpaq did not outperform zip, or gz.  If you do want to compress with Zpaq, simply use PiSafe to create a .img file.  Then compress that with Zpaq, or any tool you want.
Peace
